apiVersion: apps/v1
kind: Deployment 
metadata:
  name: resourceserver
  namespace: default
spec:
  replicas: 2
  selector:
      matchLabels:
          app: resourceserver 
  template:
      metadata:
          labels:
              app: resourceserver 

      spec:
        containers:
        - name: resourceserver
          image: kubemaster01.kubernetes.ka.xcore.net:443/resourceserver
          ports:
          - containerPort: 8080
        imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: resourceserver
  namespace: default
spec: 
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
  selector:
    app: resourceserver
